config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'sleep_tracker#track'
  post :sleep, to: 'sleep_tracker#sleep'
  post :wake, to: 'sleep_tracker#wake'

  resources :sleep_records, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sleep_record.rb
class SleepRecord < ApplicationRecord
  validates :sleep_time, presence: true

  def self.last_unfinished
    self.where(wake_time: nil).last
  end

  def self.last_unfinished_for(user_id:)
    raise NotImplementedError
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sleep_records_controller.rb
class SleepRecordsController < ApplicationController
  def show
    @sleep_record = SleepRecord.find(params.fetch(:id))
  end

  def edit
    @sleep_record = SleepRecord.find(params.fetch(:id))
  end

  def update
    @sleep_record = SleepRecord.find(params.fetch(:id))
    @sleep_record.update_attributes!(sleep_record_params)
    redirect_to sleep_record_path(@sleep_record)
  end

  private
    def sleep_record_params
      params.require(:sleep_record).permit(:sleep_time, :wake_time)
    end
end

app/controllers/sleep_tracker_controller.rb
require './lib/sleep_recorder'

class SleepTrackerController < ApplicationController
  def track
    @sleep_record = SleepRecorder.last_unfinished_record_for(@user)
  end

  def sleep
    SleepRecorder.start_sleep
    redirect_to sleep_tracker_track_path
  end

  def wake
    sleep_record = SleepRecorder.stop_sleep_for
    redirect_to edit_sleep_record_path(sleep_record)
  end

  private
  def sleep_tracker_track_path
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sleep_records_helper.rb
module SleepRecordsHelper
  class MyDuration < ActiveSupport::Duration
    def hours
      parts[:hours]
    end

    def minutes
      parts[:minutes]
    end

    def to_s
      "%d:%02d" % [hours, minutes]
    end
  end

  def duration_between(start, stop)
    start = start.in_time_zone
    stop = stop.in_time_zone
    seconds = (stop - start).to_i
    MyDuration.build(seconds)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SleepTracker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/sleep_records/edit.html.haml
%h1 Edit Sleep Record
.container
  = form_for @sleep_record do |f|
    .form-group.row
      = f.label :sleep_time, class: 'col-md-5'
      = f.datetime_field :sleep_time, class: 'form-control col-md-7'
    .form-group.row
      = f.label :wake_time, class: 'col-md-5'
      = f.datetime_field :wake_time, class: 'form-control col-md-7'
    .form-group.row
      .col-md-12
        = f.submit class: 'btn btn-primary float-right'

app/views/sleep_records/show.haml
%h1 Sleep Record
%table
  %tr
    %td Sleep Time
    %td= @sleep_record.sleep_time
  %tr
    %td Wake Time
    %td= @sleep_record.wake_time
  %tr
    %td Duration
    %td= duration_between(@sleep_record.sleep_time, @sleep_record.wake_time)

app/views/sleep_tracker/track.haml
- if @sleep_record
  = button_to 'Wake Up', wake_path, class: 'btn btn-primary'
- else
  = button_to 'Go To Sleep', sleep_path, class: 'btn btn-primary'